
name: Testing non OMV scripts

on:
  push:
    branches: [ main, development, experimental ]
  pull_request:
    branches: [ main, development, experimental ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}


    - name: Test notebooks
      run: |

        pip install -r requirements.txt

        pip install nbmake 

        pytest --nbmake CellNetworkBuilder.ipynb
        
        # pytest --nbmake Replay.ipynb # temp disable...
        


    - name: Final version info
      run: |
        pip list
        env
